// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using at_prueba_tecnica_backend.Infrastructure.Persistence;

#nullable disable

namespace at_prueba_tecnica_backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421_SeedUserRole")]
    partial class SeedUserRole
    {
    }
}
